# Generated by Django 6.0.4 on 2026-05-03 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_department_user_alter_department_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionlog',
            name='date_recorded',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='SustainabilityGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('target_value', models.FloatField()),
                ('current_value', models.FloatField(default=0.0)),
                ('deadline', models.DateField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
