# Generated by Django 6.0.4 on 2026-05-05 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_department_user_department_managed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Electricity', 'Electricity (kWh)'), ('Water', 'Water (Liters)'), ('Petrol', 'Petrol (Liters)'), ('Diesel', 'Diesel (Liters)'), ('Travel', 'Business Travel (km)')], max_length=50)),
                ('quantity', models.FloatField()),
                ('emissions_amount', models.FloatField(blank=True, null=True)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('activity_date', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.department')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
