# Generated by Django 6.0.4 on 2026-05-05 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_activitylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
