# Generated by Django 6.0.4 on 2026-05-05 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Electricity', 'Electricity'), ('Water', 'Water'), ('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Travel', 'Travel')], max_length=20)),
                ('quantity', models.FloatField(help_text='Units consumed (kWh / litres / km)')),
                ('emissions_amount', models.FloatField(editable=False, help_text='Auto-calculated: quantity × emission factor')),
                ('activity_date', models.DateField()),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.department')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activity_date', '-date_recorded'],
            },
        ),
    ]
