# Generated by Django 6.0.4 on 2026-05-08 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Human-readable event description shown in the dashboard.', max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_activities', to='core.organization')),
            ],
            options={
                'verbose_name': 'Dashboard Activity',
                'verbose_name_plural': 'Dashboard Activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
