# Generated by Django 6.0.4 on 2026-05-11 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_dashboardactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Short goal name shown in the dashboard (e.g. 'Q3 2025 Reduction Target').", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional longer description / notes.', null=True)),
                ('target_kg', models.FloatField(help_text='Maximum allowable CO₂ in kg for the entire goal period.')),
                ('start_date', models.DateField(help_text='First day of the measurement window.')),
                ('end_date', models.DateField(help_text='Last day of the measurement window.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACHIEVED', 'Achieved'), ('FAILED', 'Failed'), ('UPCOMING', 'Upcoming')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_goals', to='core.organization')),
            ],
            options={
                'verbose_name': 'Carbon Goal',
                'verbose_name_plural': 'Carbon Goals',
                'ordering': ['-start_date'],
            },
        ),
    ]
